version: '3.1'

services:
  api:   
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api_backend
    ports:      
      - '${API_PORT}:${API_PORT}'   
    volumes:     
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true 

  db:
    build: ./db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./databases:/var/lib/mysql

  adminer:
    build: ./adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:${ADMINER_PORT}'